train_batch_size: 64
downstream_batch_size: 64
crop_readout_dim: False
subst_with_orig: 0.5
experiment:
  name: KspaceLineDetection(T2Star)_ThreshClass_3D
  task: train
  weights:
device: gpu
configurator:
  module_name: core.Configurator
  class_name: DLConfigurator
  params: {}
model:
  module_name: model_zoo.cnn_line_detection
  class_name: RealValCNNLineDetNew
  params:
    input_dim: 2
    input_size: [12, 92, 112]
    crop_readout: False
    output_size: [1, 92]
    first_filters: 8
    last_filters: [8]
    kernel_size: 3
    num_layer: 4
    activation: "relu"
    normalization: "BatchNorm"
    dropout: 0.2
trainer:
  module_name: projects.kspace_line_detection.Trainer
  class_name: PTrainer
  params:
    checkpoint_path: ./weights/    # Ensure this path is correct
    nr_epochs: 300
    patience: 300
    loss:
      module_name: optim.losses.classification_losses
      class_name: WeightedCrossEntropyAcrossLines
      params:
        weight_cl0: 5
    optimizer_params:
      lr: 5.0e-4
      weight_decay: 1.0e-3
  data_loader:
    module_name: data.T2star_loader
    class_name: T2starLoader
    params:
      args:
        batch_size: 64
        data_dir:
          train: './data/links_to_data/train_T2star_b0_rigid_Fold_1/'
          val: './data/links_to_data/val_T2star_b0_rigid_Fold_1/'
          test: './data/links_to_data/test_T2star_b0_rigid_Fold_1/'
        only_brainmask_slices: True
        bm_thr: 0.3
        normalize: "line_wise"
        soft_mask: False
        subst_with_orig: 0.5
        crop_readout: False
downstream_tasks:
  T2StarLineDetection:
    module_name: projects.kspace_line_detection.DownstreamEvaluator
    class_name: PDownstreamEvaluator
    checkpoint_path: ./output_path/    # Ensure this path is correct
    data_loader:
      module_name: data.T2star_loader
      class_name: T2starLoader
      params:
        args:
          batch_size: 64
          only_brainmask_slices: True
          bm_thr: 0.3
          normalize: "line_wise"
          soft_mask: False
          subst_with_orig: 0.5
          crop_readout: False
      datasets:
        train:
          data_dir:
            test: './data/links_to_data/train_T2star_b0_rigid_Fold_1/'
        val:
          data_dir:
            test: './data/links_to_data/val_T2star_b0_rigid_Fold_1/'
        test:
          data_dir:
            test: './data/links_to_data/test_T2star_b0_rigid/'
